### ISSUE TITLE
KDL IK Solver with SVD

### ISSUE THREAD

**Issue by h3ngy1ng** [moveit/moveit2#2948]
[rookie] in moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp (https://github.com/moveit/moveit2/blob/main/moveit_kinematics/kdl_kinematics_plugin/src/kdl_kinematics_plugin.cpp), the codes utilizes ChainIkSolverVelMimicSVD to solve for IK, wondering:
1. why do we use SVD to compute the determinent and handles singularities
2. is there any way we can change the computation method? like LU decomposition/ QR decomposition
3. if yes, how do we configure it? 

thanks.

**Comment by rhaschke** [comment]
SVD is a robust method to determine the inverse Jacobian, because it allows for simple regularization of inverse singular values. LU or QR decomposition doesn't allow that, but simply inverts the matrix. There is also the `lma_kinematics` plugin, which uses the Levenberg-Marquardt algorithm instead. If you want to use another solver, I suggest to implement it yourself based on the `kdl_kinematics` plugin.
